const common = [
  "getUser",
  "updateUser",
  "getContest",
  "getContestForDashboard",
  "getAllContests",
  "getQuiz",
  "getAllQuizzes",
  "getQuestion",
  "getAllMCQS",
  "getAllChallenges",
  "createSubmission",
  "compiler",
  "getTestCases",
  "executeContestChallenge",
  "getSubmission",
  "createExecution",
  "getExecution",
  "updateExecution",
];
const student = [...common];
const admin = [
  ...common,
  "createUser",
  "deleteUser",
  "createBulkUsers",
  "getAllUsers",
  "createContest",
  "updateContest",
  "deleteContest",
  "createQuestion",
  "updateQuestion",
  "createQuiz",
  "updateQuiz",
  "createTestCase",
  "updateTestCase",
  "createMultipleTestCases",
  "deleteQuestion",
  "errorLogs",
  "deleteTestCase",
  "deleteQuiz",
  "exportSubmissions",
  "exportUsers",
  "adminDashboard",
  "exportSampleUsersDetails",
];

module.exports = {
  API: { student, admin },
};
